# @package _global_

defaults:
  - _self_
  - data: contactpoint # choose datamodule with `test_dataloader()` for evaluation
  - model: contactpoint
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "${paths.check_dir}/last.ckpt"


